packages:
  - 'apps/*'
  - 'packages/*'

allowBuilds:
  'esbuild': true
  'proto-ikons-wc': true
  'proto-tailwindcss-clrs': true

minimumReleaseAgeExclude:
  - bumpp@12.2.2
  - proto-ikons-wc@0.1.96
