/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface ProtoIkonLoader {
        /**
          * @default 'currentColor'
         */
        "hex": string;
        /**
          * @default undefined
         */
        "label": string;
        /**
          * @default 'slug'
         */
        "name": string;
        /**
          * @default false
         */
        "selected": boolean;
        /**
          * @default undefined
         */
        "size": number;
    }
    interface ProtoIkonRaw {
        /**
          * @default 'currentColor'
         */
        "hex": string;
        /**
          * @default undefined
         */
        "label": string;
        /**
          * @default 'slug'
         */
        "name": string;
        /**
          * @default false
         */
        "selected": boolean;
        /**
          * @default undefined
         */
        "size": number;
    }
}
declare global {
    interface HTMLProtoIkonLoaderElement extends Components.ProtoIkonLoader, HTMLStencilElement {
    }
    var HTMLProtoIkonLoaderElement: {
        prototype: HTMLProtoIkonLoaderElement;
        new (): HTMLProtoIkonLoaderElement;
    };
    interface HTMLProtoIkonRawElement extends Components.ProtoIkonRaw, HTMLStencilElement {
    }
    var HTMLProtoIkonRawElement: {
        prototype: HTMLProtoIkonRawElement;
        new (): HTMLProtoIkonRawElement;
    };
    interface HTMLElementTagNameMap {
        "proto-ikon-loader": HTMLProtoIkonLoaderElement;
        "proto-ikon-raw": HTMLProtoIkonRawElement;
    }
}
declare namespace LocalJSX {
    interface ProtoIkonLoader {
        /**
          * @default 'currentColor'
         */
        "hex"?: string;
        /**
          * @default undefined
         */
        "label"?: string;
        /**
          * @default 'slug'
         */
        "name"?: string;
        /**
          * @default false
         */
        "selected"?: boolean;
        /**
          * @default undefined
         */
        "size"?: number;
    }
    interface ProtoIkonRaw {
        /**
          * @default 'currentColor'
         */
        "hex"?: string;
        /**
          * @default undefined
         */
        "label"?: string;
        /**
          * @default 'slug'
         */
        "name"?: string;
        /**
          * @default false
         */
        "selected"?: boolean;
        /**
          * @default undefined
         */
        "size"?: number;
    }
    interface IntrinsicElements {
        "proto-ikon-loader": ProtoIkonLoader;
        "proto-ikon-raw": ProtoIkonRaw;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "proto-ikon-loader": LocalJSX.ProtoIkonLoader & JSXBase.HTMLAttributes<HTMLProtoIkonLoaderElement>;
            "proto-ikon-raw": LocalJSX.ProtoIkonRaw & JSXBase.HTMLAttributes<HTMLProtoIkonRawElement>;
        }
    }
}
