/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface ProtoIkonLoader {
        /**
          * @default 'currentColor'
         */
        "hex": string;
        /**
          * @default undefined
         */
        "label": string;
        /**
          * @default 'slug'
         */
        "name": string;
        /**
          * @default false
         */
        "selected": boolean;
        /**
          * @default undefined
         */
        "size": number;
    }
    interface ProtoIkonRaw {
        /**
          * @default 'currentColor'
         */
        "hex": string;
        /**
          * @default undefined
         */
        "label": string;
        /**
          * @default 'slug'
         */
        "name": string;
        /**
          * @default false
         */
        "selected": boolean;
        /**
          * @default undefined
         */
        "size": number;
    }
}
declare global {
    interface HTMLProtoIkonLoaderElement extends Components.ProtoIkonLoader, HTMLStencilElement {
    }
    var HTMLProtoIkonLoaderElement: {
        prototype: HTMLProtoIkonLoaderElement;
        new (): HTMLProtoIkonLoaderElement;
    };
    interface HTMLProtoIkonRawElement extends Components.ProtoIkonRaw, HTMLStencilElement {
    }
    var HTMLProtoIkonRawElement: {
        prototype: HTMLProtoIkonRawElement;
        new (): HTMLProtoIkonRawElement;
    };
    interface HTMLElementTagNameMap {
        "proto-ikon-loader": HTMLProtoIkonLoaderElement;
        "proto-ikon-raw": HTMLProtoIkonRawElement;
    }
}
declare namespace LocalJSX {
    interface ProtoIkonLoader {
        /**
          * @default 'currentColor'
         */
        "hex"?: string;
        /**
          * @default undefined
         */
        "label"?: string;
        /**
          * @default 'slug'
         */
        "name"?: string;
        /**
          * @default false
         */
        "selected"?: boolean;
        /**
          * @default undefined
         */
        "size"?: number;
    }
    interface ProtoIkonRaw {
        /**
          * @default 'currentColor'
         */
        "hex"?: string;
        /**
          * @default undefined
         */
        "label"?: string;
        /**
          * @default 'slug'
         */
        "name"?: string;
        /**
          * @default false
         */
        "selected"?: boolean;
        /**
          * @default undefined
         */
        "size"?: number;
    }

    interface ProtoIkonLoaderAttributes {
        "hex": string;
        "name": string;
        "selected": boolean;
        "size": number;
        "label": string;
    }
    interface ProtoIkonRawAttributes {
        "hex": string;
        "name": string;
        "selected": boolean;
        "size": number;
        "label": string;
    }

    interface IntrinsicElements {
        "proto-ikon-loader": Omit<ProtoIkonLoader, keyof ProtoIkonLoaderAttributes> & { [K in keyof ProtoIkonLoader & keyof ProtoIkonLoaderAttributes]?: ProtoIkonLoader[K] } & { [K in keyof ProtoIkonLoader & keyof ProtoIkonLoaderAttributes as `attr:${K}`]?: ProtoIkonLoaderAttributes[K] } & { [K in keyof ProtoIkonLoader & keyof ProtoIkonLoaderAttributes as `prop:${K}`]?: ProtoIkonLoader[K] };
        "proto-ikon-raw": Omit<ProtoIkonRaw, keyof ProtoIkonRawAttributes> & { [K in keyof ProtoIkonRaw & keyof ProtoIkonRawAttributes]?: ProtoIkonRaw[K] } & { [K in keyof ProtoIkonRaw & keyof ProtoIkonRawAttributes as `attr:${K}`]?: ProtoIkonRawAttributes[K] } & { [K in keyof ProtoIkonRaw & keyof ProtoIkonRawAttributes as `prop:${K}`]?: ProtoIkonRaw[K] };
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "proto-ikon-loader": LocalJSX.IntrinsicElements["proto-ikon-loader"] & JSXBase.HTMLAttributes<HTMLProtoIkonLoaderElement>;
            "proto-ikon-raw": LocalJSX.IntrinsicElements["proto-ikon-raw"] & JSXBase.HTMLAttributes<HTMLProtoIkonRawElement>;
        }
    }
}
